name: CI
on: push

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: "0.110.0"

      - name: Build
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3

        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: pretentiousUsername/pretentioususername.github.io
          publish_dir: ./public
          user_name: pretentiousUsername
          user_email: ${{ secrets.EMAIL }} # it isn't really secret but lol
          publish_branch: main
